name: graph_ownership_verification
channels:
  - pytorch
  - dglteam
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=4.0.1
  - attrs=21.4.0
  - backcall=0.2.0
  - blas=1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.26
  - cachetools=4.2.2
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - cryptography=3.4.8
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.18
  - decorator=5.1.1
  - dgl-cuda11.3=0.7.2
  - expat=2.4.4
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - frozenlist=1.2.0
  - gast=0.4.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpcio=1.42.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.8.2
  - intel-openmp=2021.4.0
  - ipython=7.31.1
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9d
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - networkx=2.6.3
  - nltk=3.6.5
  - numpy=1.21.2
  - numpy-base=1.21.2
  - oauthlib=3.1.1
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1m
  - opt_einsum=3.3.0
  - packaging=21.3
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - prompt-toolkit=3.0.20
  - protobuf=3.19.1
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - pytorch=1.10.2
  - pytorch-mutex=1.0=cuda
  - qt=5.9.7
  - readline=8.1.2
  - regex=2021.11.2
  - requests=2.27.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.37.2
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.6.0
  - termcolor=1.1.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - torchaudio=0.10.2
  - torchvision=0.11.3
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - werkzeug=2.0.2
  - wheel=0.37.1
  - wrapt=1.13.3
  - xz=5.2.5
  - yarl=1.6.3
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - gensim==4.1.2
    - llvmlite==0.38.0
    - numba==0.55.1
    - pandas==1.4.0
    - pytz==2021.3
    - pyyaml==6.0
    - smart-open==5.2.1
    - tabulate==0.8.9
    - yacs==0.1.8
    - hydra-core==1.1.2